#nav
home: 主页
archive: 归档
archive_a: 文章归档
archive_b: 归档：%s
categories: 分类
tags: 标签
about: 关于
gallery: 相册
search: 搜索
friend: 友链

#navgation
prev: 上一页
next: 下一页
prev_post: 上一篇
next_post: 下一篇
load_more: 加载更多
load_end: 没有了
to_top: 返回顶部

#page
page: 第 %d 页

#archive page
total: 总计
pian: 篇
post: 文章

#tag & category page
ge: 个
tag_tags: 标签
category_categories: 分类


#post
current_post: 当前文章
recent_posts: 最新文章
related_posts: 相关文章
publish_date: 发布于
update_date: 更新于
split_line: /
toc: 文章目录
tweets: 推文
comment: 评论
hits: 热度
likes: 喜欢
load_comment: 加载评论
no_content: 没有文章内容...
view_all: 阅读全文
share: 分享

#others
powered_by: Powered by
rss_feed: RSS Feed
download: 下载
is_download: 确认下载